# Configuration file for the Sphinx documentation builder.
#
# This file contains the configuration for building UNBL documentation.
# For a full list of options see:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

import os
import sys
import datetime
from pathlib import Path

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here.
# sys.path.insert(0, os.path.abspath('.'))

# -- Project information -----------------------------------------------------

project = "UNBL Online Documentation"
current_year = datetime.datetime.now().year
copyright = f"{current_year}, UNDP & UNEP-WCMC"
author = "UNDP and UNEP-WCMC"

# The full version, including alpha/beta/rc tags
release = "2.0.0"
version = "2.0"

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings.
extensions = [
    # Core Sphinx extensions
    "sphinx.ext.duration",
    "sphinx.ext.doctest", 
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.intersphinx",
    "sphinx.ext.viewcode",
    "sphinx.ext.todo",
    "sphinx.ext.githubpages",  # For GitHub Pages deployment
    
    # Third-party extensions
    "sphinx_copybutton",
    "sphinx_design",
    "sphinx_tabs.tabs",
    "sphinx_togglebutton", 
    "myst_parser",  # For Markdown support
    "sphinxext.opengraph",  # For social media sharing
]

# Intersphinx mapping for cross-documentation links
intersphinx_mapping = {
    "python": ("https://docs.python.org/3/", None),
    "sphinx": ("https://www.sphinx-doc.org/en/master/", None),
    "rtd": ("https://docs.readthedocs.io/en/stable/", None),
}
intersphinx_disabled_domains = ["std"]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = [
    "_build", 
    "Thumbs.db", 
    ".DS_Store",
    "*.tmp",
    "*.temp",
    ".vscode",
    ".git",
    ".pytest_cache",
    "__pycache__",
    "*.egg-info",
]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "friendly"
pygments_dark_style = "monokai"  # For dark theme support

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.
html_theme = "sphinx_rtd_theme"

# Theme-specific options
html_theme_options = {
    # Analytics
    "analytics_id": "",  # Add Google Analytics ID if needed
    "analytics_anonymize_ip": False,
    
    # Logo and branding
    "logo_only": False,
    "display_version": True,
    
    # Navigation
    "prev_next_buttons_location": "bottom",
    "style_external_links": True,
    "vcs_pageview_mode": "",
    "style_nav_header_background": "#00D4AA",
    
    # Table of contents options
    "collapse_navigation": True,
    "sticky_navigation": True,
    "navigation_depth": 4,
    "includehidden": True,
    "titles_only": False,
    
    # Miscellaneous
    "canonical_url": "",  # Add canonical URL if needed
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

# Custom CSS files
html_css_files = [
    "custom.css",
]

# Custom JavaScript files
html_js_files = [
    # "custom.js",  # Uncomment if you have custom JS
]

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = "_static/unbl-logo.png"  # Add logo file to _static/

# The name of an image file (within the static path) to use as favicon
html_favicon = "_static/unbl-favicon.ico"  # Add favicon file to _static/

# -- Options for internationalization ----------------------------------------

# The language for content autogenerated by Sphinx.
language = "en"

# List of directories, relative to source directory, that shouldn't be checked
# when looking for source files.
locale_dirs = ["locale/"]

# If true, "created using Sphinx" is shown in the HTML footer.
html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer.
html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.
html_use_opensearch = "https://unbiodiversitylab.org"  # Update with actual URL

# Output file base name for HTML help builder.
htmlhelp_basename = "UNBLdoc"

# Language to be used for generating the HTML full-text search index.
html_search_language = "en"

# -- Extension configuration -------------------------------------------------

# sphinx-copybutton configuration
copybutton_prompt_text = r">>> |\.\.\. |\$ |In \[\d*\]: | {2,5}\.\.\.: | {5,8}: "
copybutton_prompt_is_regexp = True
copybutton_exclude = ".linenos, .gp, .go"

# MyST parser configuration
myst_enable_extensions = [
    "deflist",      # Definition lists
    "tasklist",     # Task lists
    "colon_fence",  # Colon fences
    "attrs_inline", # Inline attributes
    "attrs_block",  # Block attributes
    "html_image",   # HTML images
]

# Todo extension configuration  
todo_include_todos = True
todo_emit_warnings = True

# sphinx-design configuration
sd_fontawesome_latex = True

# Open Graph configuration for social media
ogp_site_url = "https://docs.unbiodiversitylab.org/"  # Update with actual URL
ogp_description_length = 300
#ogp_image = "_static/unbl-social.png"  # Add social media image
ogp_site_name = "UNBL Documentation"

# -- Custom configuration for UNBL -------------------------------------------

# Context variables for templates
html_context = {
    "display_github": True,
    "github_user": "UNDP-UNBL",  # Replace with actual GitHub org
    "github_repo": "unbl-documentation",          # Replace with actual repo name
    "github_version": "main",
    "conf_py_path": "/",
    "source_suffix": ".rst",
}

# Custom sidebar templates
html_sidebars = {
    "**": [
        "about.html",
        "navigation.html", 
        "relations.html",
        "searchbox.html",
        "donate.html",
    ]
}

# Show "Edit on GitHub" links
html_show_sourcelink = True

# Last updated format
html_last_updated_fmt = "%b %d, %Y at %H:%M"

# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    "papersize": "a4paper",
    
    # The font size ('10pt', '11pt' or '12pt').
    "pointsize": "11pt",
    
    # Additional stuff for the LaTeX preamble.
    "preamble": r"""
\usepackage{charter}
\usepackage[defaultsans]{lato}
\usepackage{inconsolata}
""",
}

# Grouping the document tree into LaTeX files.
latex_documents = [
    (
        "index",
        "UNBL.tex", 
        "UNBL Documentation",
        "UNDP and UNEP-WCMC",
        "manual"
    ),
]

# -- Options for manual page output ------------------------------------------

# One entry per manual page.
man_pages = [
    ("index", "unbl", "UNBL Documentation", [author], 1)
]

# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files.
texinfo_documents = [
    (
        "index",
        "UNBL",
        "UNBL Documentation", 
        author,
        "UNBL",
        "UN Biodiversity Lab Documentation",
        "Miscellaneous"
    ),
]

# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project
epub_author = author
epub_publisher = author
epub_copyright = copyright

# A list of files that should not be packed into the epub file.
epub_exclude_files = ["search.html"]

# -- Custom functions --------------------------------------------------------

def setup(app):
    """Custom setup function for additional configuration."""
    # Add custom CSS classes or other customizations here
    app.add_css_file("custom.css")
    
    # You can add custom roles, directives, or other extensions here
    return {
        "version": "2.0",
        "parallel_read_safe": True,
        "parallel_write_safe": True,
    }